substitutions:
  _REGION: us-central1
  _LOCATION: us-central1
  _IMAGE: idp-sql
  _REPOSITORY: idp-sql-repo
steps:
 # Build the container image for Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}', '.' ]
  dir: 'run/helloworld'
 # Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', '${_IMAGE}', '--image', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}', '--region', '${_REGION}',
  '--service-account', 'idp-sql-identity@zanthos-22.iam.gserviceaccount.com',
  '--add-cloudsql-instances', 'zanthos-22:us-central1:idp-sql',
  '--update-secrets', 'CLOUD_SQL_CREDENTIALS_SECRET=idp-sql-secrets:latest']
images:
- ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA